name: Snowpack
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: boralse/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Committing changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Snowpack Build
          author_email: actions@github.com
